services:
  db:
    image: postgres:15-alpine
    container_name: url_shortener_db
    restart: always
    environment:
      - POSTGRES_DB=UrlShortenerDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_secret_password 
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: